name       : gnome-initial-setup
version    : 3.22.1
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-initial-setup/3.22/gnome-initial-setup-3.22.1.tar.xz : 56a663d84ab16854afbdd5ea852f0b76bb5e30829f14f3a224ea130c14825468
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME Initial Setup
description: |
    GNOME Initial Setup utility
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gdm)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(iso-codes)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(rest-0.7)
    - pkgconfig(webkit2gtk-4.0)
rundeps    :
    - geoclue
    - libgnomekbd
setup      : |
    # Note, in future when Cheese is fixed, add cheese-gtk to build deps
    # Find something nicer that works with multiple desktops/distros
    %patch -p1 < $pkgfiles/0001-Set-budgie-desktop-to-be-the-default-xsession-if-it-.patch
    %configure
build      : |
    %make
install    : |
    %make_install

    install -D -m 00644 $pkgfiles/gnome-initial-setup.conf $installdir/%libdir%/sysusers.d/gnome-initial-setup.conf
    mkdir -p ${installdir}/var/lib/gnome-initial-setup
